export { IoClientModule } from './io-client.module'
export { InjectIoClientProvider, EventListener, OnConnect, OnDisconnect, OnConnectError } from './io-client.decorators'
export { IoClientModuleOptions, IoClientModuleAsyncOptions, IoClientEventMetadata } from './io-client.interface'
export { getIoClientToken } from './io-client.utils'
export { protocol, Manager, ManagerOptions, Socket as IoClient, io, SocketOptions } from 'socket.io-client'
